# Generated by Django 5.1.7 on 2025-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de creacion')),
            ],
        ),
    ]
