# Generated by Django 5.1.7 on 2025-04-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='PC', max_length=30)),
                ('identificador', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AddField(
            model_name='equipo',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.red'),
        ),
    ]
